# Test 2024-04-18 at 18:18:31

name: Test

on:
  push:
    paths:
      - '**/main.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Test Web Server
      run: |
        java webServer.java &
        sleep 4 # Web server has to have time to compile and start
        curl -s -o zzz.txt -X POST   -H "Content-Type: application/json" -d '{"key1":"value1","key2":"value2"}'   http://localhost:8080/aaa/bbb
        ls -la

    - name: Test Web Server output
      run: |
        cat zzz.txt

    - name: Empty Url
      run: |
        java webServer.java &
        sleep 4
        curl -s -o zzz2.txt -X POST   -H "Content-Type: application/json" -d '{"key1":"value1","key2":"value2"}'   http://localhost:8080
        ls -la

    - name: Test Web Server output
      run: |
        cat zzz2.txt
